---
- name: install supervisor
  apt: name=supervisor
  become: true
  tags: superuser

- name: create log dir
  file: name='{{ log_path }}' state=directory

- name: create supervisor config dir
  file: name='{{ supervisor_config_dir }}' state=directory mode='{{ supervisor_manage_mode }}'
        owner='{{ supervisor_manage_user }}' group='{{ supervisor_manage_group }}'
  become: true
  tags: superuser
  notify: reload supervisord

- name: configure supervisord
  template: src=supervisord.conf.j2 dest=/etc/supervisor/supervisord.conf
  become: true
  tags: superuser
  notify: reload supervisord

- name: configure supervisor group
  template:
    src: supervisor.conf.j2
    dest: '{{ supervisor_config_dir }}/{{ group_name }}.conf'
  when: supervisor_group and supervisor_use_sudo
  notify: reload supervisor group
  become: true
  tags: superuser

- name: configure supervisor group
  template:
    src: supervisor.conf.j2
    dest: '{{ supervisor_config_dir }}/{{ group_name }}.conf'
  when: supervisor_group and not supervisor_use_sudo
  notify: reload supervisor group

- name: make sure supervisor is running
  service: name=supervisor state=started
  become: true
  tags: superuser
