---
- name: install supervisor
  apt: name=supervisor
  become: true
  tags: superuser

- name: create log dir
  file: name='{{ log_path }}' state=directory

- name: configure supervisor group
  template:
    src: supervisor.conf.j2
    dest: '/etc/supervisor/conf.d/{{ group_name }}.conf'
  become: true
  tags: superuser
  when: servers|length > 0
  notify: reload supervisor group
