---
- name: reload supervisor group
  supervisorctl: name='{{ group_name }}:' state=restarted
  #tags: [superuser, upgrade]
  listen: "reload app"
  ignore_errors: supervisor_ignore_handler_errors
  become: true
  when: '{{ supervisor_reload }} and {{ supervisor_group }} and {{ supervisor_use_sudo }}'

- name: reload supervisor
  supervisorctl: name='{{ program_name }}' state=restarted
  ignore_errors: supervisor_ignore_handler_errors
  listen: "reload app"
  become: true
  when: '{{ supervisor_reload }} and {{ supervisor_single }} and {{ supervisor_use_sudo }}'

- name: reload supervisor group
  supervisorctl: name='{{ group_name }}:' state=restarted
  listen: "reload app"
  ignore_errors: supervisor_ignore_handler_errors
  when: '{{ supervisor_reload }} and {{ supervisor_group }} and not {{ supervisor_use_sudo }}'

- name: reload supervisor
  supervisorctl: name='{{ program_name }}' state=restarted
  ignore_errors: supervisor_ignore_handler_errors
  listen: "reload app"
  when: '{{ supervisor_reload }} and {{ supervisor_single }} and not {{ supervisor_use_sudo }}'
